name: SPAC flow docker snapshot
description: SPAC flow docker snapshot

inputs:
  current_branch:
    required: true
  docker_labels:
    required: false
    default: |
      maintainer=https://pagopa.it
      org.opencontainers.image.source=https://github.com/${{ github.repository }}
  enable_azure_devops_step:
    required: false
    default: false
  azure_devops_apps:
    required: false
  azure_devops_project_url:
    required: false
  azure_pipeline_name:
    required: false
  AZUREDEVOPS_PAT:
    required: false
    default: ''

runs:
  using: "composite"
  steps:
      - name: Check AZUREDEVOPS_PAT
        if: ${{ inputs.enable_azure_devops_step == 'true' }}
        shell: bash
        run: |
          if [ -z "${{ inputs.AZUREDEVOPS_PAT }}" ]; then
            echo "Error: AZUREDEVOPS_PAT is empty. This is required for triggering the Azure DevOps pipeline."
            exit 1
          fi

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set Docker tags
        id: set_docker_tags
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "DOCKER_TAGS=ghcr.io/${{ github.repository }}:develop-latest,ghcr.io/${{ github.repository }}:snapshot" >> $GITHUB_OUTPUT
          else
            echo "DOCKER_TAGS=ghcr.io/${{ github.repository }}:snapshot,ghcr.io/${{ github.repository }}:snapshot-${{ inputs.current_branch }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.set_docker_tags.outputs.DOCKER_TAGS }}
          labels: ${{ inputs.docker_labels }}

      - name: Trigger Azure DevOps pipeline
        if: ${{ inputs.enable_azure_devops_step == 'true' }}
        uses: jacopocarlini/azure-pipelines@v1.3
        with:
          azure-devops-project-url: ${{ inputs.azure_devops_project_url }}
          azure-pipeline-name: ${{ inputs.azure_pipeline_name }}
          azure-devops-token: ${{ inputs.AZUREDEVOPS_PAT }}
          azure-template-parameters: |
            {
                "APPS": "${{ inputs.azure_devops_apps }}",
                "POSTMAN_BRANCH": "${{ inputs.current_branch }}"
            }
          azure-pipeline-variables: '{"system.debug": "true"}'
