name: Make Release
description: "Make a new release on GitHub"

inputs:
  github_token:
    required: true
    type: string
    description: Github Token with Admin privileges
  semver:
    required: true
    type: choice
    description: Select the new Semantic Version
    options:
      - major
      - minor
      - patch
      - buildNumber
      - skip
  skip_ci:
    required: false
    type: boolean
    description: True you want skip the CI workflows on release commit
    default: true
  beta:
    required: false
    type: boolean
    description: True if it is a beta version (update canary helm version)
    default: false
  jdk_version:
    required: false
    type: choice
    description: Select the JDK version
    default: 11
    options:
      - 11
      - 17
  prerelease:
    required: false
    type: boolean
    description: True if it is a prerelease
    default: false


outputs:
  version:
    description: "New Version"
    value: ${{ steps.semver.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Input Log
      run: |
        echo "📝 Inputs"
        echo "semver: ${{ inputs.semver}}" 
        echo "beta: ${{ inputs.beta}}"
        echo "skip_ci: ${{ inputs.skip_ci}}"
        echo "jdk version: ${{ inputs.jdk_version}}"
      shell: bash

    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.github_token }}

    - name: Update Semantic Version
      id: semver
      uses: pagopa/github-actions-template/maven-semver@main
      with:
        semver: ${{inputs.semver}}
        beta: ${{inputs.beta}}
        jdk_version: ${{inputs.jdk_version}}


    - name: Push New Version
      if: ${{ inputs.semver != 'skip' }}
      shell: bash
      run: |
        echo "${{ steps.semver.outputs.version }}"
        git ls-files . | grep 'pom.xml'  | xargs git add
        git config --global user.email "github-bot@pagopa.it"
        git config --global user.name "pagopa-github-bot"
        git commit -m "Bump to version ${{ steps.semver.outputs.version }} ${{ (inputs.skip_ci && '[skip ci]') || '' }}" || exit 0
        git push origin ${{ github.ref_name}}

    - name: Create Release
      if: ${{ inputs.semver != 'skip' }}
      uses: ncipollo/release-action@v1.12.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        commit: ${{ github.ref_name }}
        tag: ${{ steps.semver.outputs.version }}
        name: Release ${{ steps.semver.outputs.version }}
        makeLatest: latest
        generateReleaseNotes: true
        prerelease: ${{ inputs.prerelease }}
