name: Make Release
description: "Make a new release on GitHub"

inputs:
  github_token:
    required: true
    type: string
    description: Github Token with Admin privileges
  semver:
    required: true
    type: choice
    description: Select the new Semantic Version
    options:
      - major
      - minor
      - patch
      - buildNumber
      - skip
  beta:
    required: true
    type: boolean
    description: True if it is a beta version (update canary helm version)

outputs:
  version:
    description: "New Version"
    value: ${{ steps.semver.outputs.app_version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name}}
        token: ${{ inputs.github_token }}

    - name: Update Semantic Version
      id: semver
      uses: pagopa/github-actions-template/maven-semver@mave-version-beta
      with:
        semver: ${{inputs.semver}}
        beta: ${{inputs.beta}}

    - name: Push New Version
      if: ${{ inputs.semver != 'skip' }}
      shell: bash
      run: |
        echo "${{ steps.semver.outputs.app_version }}"
        git ls-files . | grep 'pom.xml'  | xargs git add
        git config --global user.email "github-bot@pagopa.it"
        git config --global user.name "pagopa-github-bot"
        git commit -m "Bump version [skip ci]" || exit 0
        git push origin ${{ github.ref_name}}

    - name: Create Release
      if: ${{ inputs.semver != 'skip' }}
      uses: ncipollo/release-action@v1.12.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag: ${{ steps.semver.outputs.app_version }}
        name: Release ${{ steps.semver.outputs.app_version }}
        makeLatest: latest
        generateReleaseNotes: true
        prerelease: ${{ (inputs.beta && 'true') || 'false' }}
