name: Make Release
description: "Make a new release on GitHub"

inputs:
  github_token:
    required: true
    type: string
    description: Github Token with Admin privileges
  semver:
    required: true
    type: choice
    description: Select the new Semantic Version
    options:
      - major
      - minor
      - patch
      - buildNumber
      - skip
  skip_ci:
    required: false
    type: boolean
    description: True you want skip the CI workflows on release commit
    default: true

outputs:
  version:
    description: "New Version"
    value: ${{ steps.semver.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Input Log
      run: |
        echo "ðŸ“ Inputs"
        echo "semver: ${{ inputs.semver}}" 
        echo "skip_ci: ${{ inputs.skip_ci}}"
      shell: bash

    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.github_token }}

    - name: Set Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.10.0

    - id: get_version
      name: Get Version
      run: |
        PACKAGE_FILE="package.json"
        if [[ -f "$PACKAGE_FILE" ]]; then
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Bump Package Version
      id: bump
      if: ${{ inputs.semver != 'skip' }}
      uses: pagopa/github-actions-template/bump-semver@main
      with:
        semver: ${{ inputs.semver  }}
        current_version: ${{ steps.get_version.outputs.version }}

    - name: Set branch
      run: |
        echo "BRANCH=-${{github.ref_name}}" >> $GITHUB_ENV
      if: ${{ github.ref_name != 'main' }}
      shell: bash

    - name: Push New Version
      if: ${{ inputs.semver != 'skip' }}
      shell: bash
      run: |
        contents="$(jq '.version = "${{ steps.bump.outputs.new_version }}${{env.BRANCH}}"' package.json)"
        echo -E "${contents}" > package.json
  
        git add .
        git config --global user.email "github-bot@pagopa.it"
        git config --global user.name "pagopa-github-bot"
        git commit -m "Bump to version ${{ steps.bump.outputs.new_version }} ${{ (inputs.skip_ci && '[skip ci]') || '' }}" || exit 0
        git push origin ${{ github.ref_name}}

    - name: Create Release
      if: ${{ inputs.semver != 'skip' }}
      uses: ncipollo/release-action@v1.12.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        commit: ${{ github.ref_name }}
        tag: ${{ steps.bump.outputs.new_version }}
        name: Release ${{ steps.bump.outputs.new_version }}
        makeLatest: latest
        generateReleaseNotes: true
        prerelease: ${{ (inputs.semver == 'buildNumber' && 'true') || 'false' }}
