name: Payments flow docker snapshot
description: Payments flow docker snapshot

inputs:
  current_branch:
    description: Branch used to launch the action
    required: true
  github_pat:
    description: Personal GitHub token for packages
    required: false
    default: ''
  docker_labels:
    description: Labels for docker push
    required: false
    default: |
      maintainer=https://pagopa.it
      org.opencontainers.image.source=https://github.com/${{ github.repository }}

runs:
  using: "composite"
  steps:
      # Set the appropriate token
      - name: ðŸ” Set GitHub Token
        id: set_token
        shell: bash
        run: |
          if [ -n "${{ inputs.github_pat }}" ]; then
            echo "GITHUB_AUTH_TOKEN=${{ inputs.github_pat }}" >> $GITHUB_OUTPUT
          else
            echo "GITHUB_AUTH_TOKEN=${{ github.token }}" >> $GITHUB_OUTPUT
          fi

      - name: ðŸ›ƒ Log in to the Github Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.set_token.outputs.GITHUB_AUTH_TOKEN }}

      - name: ðŸ¤” Set Docker tags
        id: set_docker_tags
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "DOCKER_TAGS=ghcr.io/${{ github.repository }}:develop-latest,ghcr.io/${{ github.repository }}:snapshot,ghcr.io/${{ github.repository }}:snapshot-${{ inputs.current_branch }}" >> $GITHUB_OUTPUT
          else
            echo "DOCKER_TAGS=ghcr.io/${{ github.repository }}:snapshot,ghcr.io/${{ github.repository }}:snapshot-${{ inputs.current_branch }}" >> $GITHUB_OUTPUT
          fi

      - name: ðŸš€ Build and push Docker image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
          context: .
          push: true
          tags: ${{ steps.set_docker_tags.outputs.DOCKER_TAGS }}
          labels: ${{ inputs.docker_labels }}
          build-args: |
            GITHUB_TOKEN=${{ steps.set_token.outputs.GITHUB_AUTH_TOKEN }}
