name: Add PR labels
description: "Add a label to PR"

inputs:
  label:
    required: true
    type: string
    default: ''
    description: The label to add
  github_token:
    required: true
    type: string
    description: Github Token

runs:
  using: "composite"
  steps:
    - name: Add label
      uses: actions/github-script@v6.3.3
      env:
          LABEL: ${{inputs.label}}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          let { LABEL } = process.env
          github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [LABEL]
            });
          
          github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The default action is to increase the PATCH number of SEMVER. Set IGNORE-FOR-RELEASE if you want to skip SEMVER bump. BREAKING-CHANGE and NEW-RELEASE must be run from GH Actions section manually.'
            });
