name: Build and Push
description: "Build and push a docker image on GitHub Container Registry"

inputs:
  tag:
    required: true
    type: string
    description: Used to tag the image (for example the version)
  build_args:
    required: false
    type: string
    description: optional docker build arguments(with format 'key=value')
  github_token:
    required: true
    type: string
    description: Github Token


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        ref: ${{ inputs.tag }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          latest
          ${{ inputs.tag }}
          type=ref,event=branch
          type=sha

    - name: Build and push
      uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build_args }}

