name: Semver
description: "Semantic Versioning"

inputs:
  semver:
    required: true
    type: choice
    description: Select the new Semantic Version
    options:
      - major
      - minor
      - patch
      - buildNumber
      - skip
  beta:
    required: true
    type: boolean
    description: True if it is a beta version (update canary helm version)
  jdk_version:
    required: false
    type: choice
    description: Select the JDK version
    default: 11
    options:
      - 11
      - 17


outputs:
  version:
    description: "New App Version"
    value: ${{ steps.get_app_version.outputs.version }}
  chart_version:
    description: "New Chart Version"
    value: ${{ steps.get_chart_version.outputs.chart_version }}

runs:
  using: "composite"
  steps:
    - name: Input Log
      run: |
        echo "ðŸ“ Inputs"
        echo "semver: ${{ inputs.semver}}" 
        echo "beta: ${{ inputs.beta}}"
        echo "jdk version: ${{ inputs.jdk_version}}"
      shell: bash

    - name: Set up JDK ${{ inputs.jdk_version}}
      uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1
      with:
        java-version: ${{ inputs.jdk_version}}
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.8.2
    - name: Cache Maven packages
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set branch
      run: |
        echo "BRANCH=-${{github.ref_name}}" >> $GITHUB_ENV
      if: ${{ github.ref_name != 'main' }}
      shell: bash

    - name: Set build-number
      run: |
        mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-${parsedVersion.nextBuildNumber}${{env.BRANCH}}'
      if: ${{ inputs.semver == 'buildNumber' }}
      shell: bash

    - name: Set major
      run: |
        mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.nextMajorVersion}.0.0${{env.BRANCH}}'
      if: ${{ inputs.semver == 'major' }}
      shell: bash

    - name: Set minor
      run: |
        mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0${{env.BRANCH}}'
      if: ${{ inputs.semver == 'minor' }}
      shell: bash

    - name: Set patch
      run: |
        mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}${{env.BRANCH}}'
      if: ${{ inputs.semver == 'patch' }}
      shell: bash

    - id: get_app_version
      name: Get Version
      run: |
        echo "ðŸ†™ Bump App Version to $(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
        echo "version=$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Helm Bump
      if: ${{ inputs.semver != 'skip' }}
      uses: pagopa/github-actions-template/helm-bump@main
      with:
        version: ${{ steps.get_app_version.outputs.version }}
        beta: ${{ inputs.beta }}


    - name: Update Openapi/Swagger Version
      if: ${{ inputs.semver != 'skip' }}
      shell: bash
      run: |
        echo "ðŸ“‘ Bump Openapi Version to ${{ steps.get_app_version.outputs.version }}"

        for i in openapi/*.json; do
          [ -f "$i" ] || break
          cat <<< "$(jq ".info.version = \"${{ steps.get_app_version.outputs.version }}\"" "$i")" > "$i"
          git add $i
        done
        for i in openapi/*.yaml; do
          [ -f "$i" ] || break
          yq -i ".info.version = \"${{ steps.get_app_version.outputs.version }}\"" "$i"
          git add "$i"
        done
        for i in openapi/*.yml; do
          [ -f "$i" ] || break
          yq -i ".info.version = \"${{ steps.get_app_version.outputs.version }}\"" "$i"
          git add "$i"
        done


