
name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # Build PR images
  pr-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Build and promote PR image (composite)
        uses: pagopa/github-actions-template/docker-golden-image-workflows/build-pr@main
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}

  # Build MA images on main
  main-build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Build and promote MA image (composite)
        uses: pagopa/github-actions-template/docker-golden-image-workflows/build-and-promote-ma@main
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
