name: Deploy container as Azure Functions
description: "Deploy container functionApp on Azure"

inputs:

  branch:
    required: true
    description: The branch to deploy
    type: string
  client_id:
    required: true
    description: Azure Client ID
    type: string
  subscription_id:
    required: true
    description: Azure Subscription ID
    type: string
  tenant_id:
    required: true
    description: Azure Tenant ID
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch}}

    - name: Login via Azure CLI
      uses: azure/login@89d153571fe9a34ed70fcf9f1d95ab8debea7a73
      with:
        client-id: ${{ inputs.CLIENT_ID }}
        tenant-id: ${{ inputs.TENANT_ID }}
        subscription-id: ${{ inputs.SUBSCRIPTION_ID }}

    # TODO review login
#    - name: 'Docker Login'
#      uses: azure/docker-login@v1
#      with:
#        login-server: ghcr.io/${{ github.repository }}
#        username: ${{ secrets.REGISTRY_USERNAME }}
#        password: ${{ secrets.REGISTRY_PASSWORD }}

#    - name: 'Compose Customized Docker Image'
#      shell: bash
#      run: |
#        # If your function app project is not located in your repository's root
#        # Please change the path to your directory for docker build
#        docker build . -t REGISTRY/NAMESPACE/IMAGE:TAG
#        docker push REGISTRY/NAMESPACE/IMAGE:TAG
#
#    - name: 'Run Azure Functions Container Action'
#      uses: Azure/functions-container-action@v1
#      id: fa
#      with:
#        app-name: PLEASE_REPLACE_THIS_WITH_YOUR_FUNCTION_APP_NAME
#        image: REGISTRY/NAMESPACE/IMAGE:TAG
