name: Semantic version Setup for Node components
description: "Setting up semantic version according to issue label"


inputs:
  semver:
    required: true
    description: The name of the image from container registry to be used
    type: string
outputs:
  semver:
    description: "Semantic Version"
    value: ${{ steps.get_semver.outputs.semver }}
  environment:
    description: "Environment"
    value: ${{ steps.output.outputs.environment }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

    - name: Branch or tag selection
      id: is_git_tag
      shell: bash
      run: |
        echo "IS_GIT_TAG=$(git tag --list | grep \"${{ github.ref_name }}\" | wc -l | bc -l)" >> $GITHUB_ENV

    # Set Environment
    - if: ${{ github.event.inputs.environment == null || github.event.inputs.environment == 'dev' }}
      shell: bash
      run: echo "ENVIRONMENT=dev" >> $GITHUB_ENV

    - if: ${{ github.event.inputs.environment == 'uat' }}
      shell: bash
      run: echo "ENVIRONMENT=uat" >> $GITHUB_ENV

    - if: ${{ github.event.inputs.environment == 'prod' }}
      shell: bash
      run: echo "ENVIRONMENT=prod" >> $GITHUB_ENV

    - if: ${{ github.event.inputs.environment == 'all' }}
      shell: bash
      run: echo "ENVIRONMENT=all" >> $GITHUB_ENV

    # Check PR
    - name: pull request rejected
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged != true
      shell: bash
      run: |
        echo "❌ PR was closed without a merge"
        exit 1

    # Set Semver
    - run: echo "SEMVER=patch" >> $GITHUB_ENV
      shell: bash

    ## The following checks analyze PR workflow

    # this is to avoid breaking-change or new-release in uat and prod env
    - if: ${{ github.event.pull_request.merged && ( github.event.inputs.environment == 'uat' || github.event.inputs.environment == 'prod') && ( contains(github.event.pull_request.labels.*.name, 'breaking-change') || contains(github.event.pull_request.labels.*.name, 'new-release') || contains(github.event.pull_request.labels.*.name, 'ignore-for-release') ) }}
      shell: bash
      run: |
        echo "❌ UAT and PROD accept only \"patch\" or \"promote\""
        exit 1

    - if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'ignore-for-release') }}
      shell: bash
      run: echo "SEMVER=skip" >> $GITHUB_ENV

    - if: ${{ github.event.pull_request.merged && ( contains(github.event.pull_request.labels.*.name, 'new-release') || contains(github.event.pull_request.labels.*.name, 'breaking-change') ) }}
      shell: bash
      run: |
        echo "❌ Only \"patch\" or \"ignore-for-release\" are accepted."
        echo "ℹ️ \"breaking-change\" and \"new-release\" must be executed only in DEV env."
        exit 1

    ## The following checks analyze manual workflow

    # force semver if dev, !=main or skip release
    - if: ${{ (inputs.semver == 'new_release' || inputs.semver == 'breaking_change') && (env.ENVIRONMENT == 'uat' || env.ENVIRONMENT == 'prod') }}
      shell: bash
      run: |
        echo "❌ UAT and PROD accept only \"patch\" or \"promote\""
        exit 1

    - if: ${{ inputs.semver == 'new_release'}}
      shell: bash
      run: echo "SEMVER=minor" >> $GITHUB_ENV

    - if: ${{ inputs.semver == 'breaking_change' }}
      shell: bash
      run: echo "SEMVER=major" >> $GITHUB_ENV

    # build-number if in dev env and deploy from specific branch
    - if: ${{ github.ref_name != 'main' && env.ENVIRONMENT == 'dev'}}
      shell: bash
      run: |
        if $semver == 'new_release' || $semver == 'breaking_change'
        then
          echo "⚠️ \"breaking-change\" and \"new-release\" are accepted only with main branch. Setting buildNumber."
        fi
        echo "SEMVER=buildNumber" >> $GITHUB_ENV
      env:
        semver: ${{inputs.semver}}

    # patch if in uat|prod env and deploy from specific branch
    - if: ${{ github.ref_name != 'main' && (env.ENVIRONMENT == 'uat' || env.ENVIRONMENT == 'prod') }}
      shell: bash
      run: echo "SEMVER=patch" >> $GITHUB_ENV

    # override previous SEMVER if in uat|prod env and deploy from specific tag
    - if: ${{ env.IS_GIT_TAG == '1' && (env.ENVIRONMENT == 'uat' || env.ENVIRONMENT == 'prod') }}
      shell: bash
      run: echo "SEMVER=skip" >> $GITHUB_ENV

    - if: ${{ github.ref_name == 'main' && (env.ENVIRONMENT == 'uat' || env.ENVIRONMENT == 'prod') }}
      shell: bash
      run: |
        echo "❌ UAT and PROD accept only \"patch\" or \"promote\" from specific TAG, custom branch (for bugfixing) but MAIN branch is not accepted"
        exit 1

    - if: ${{ inputs.semver == 'promote' || inputs.semver == 'skip' }}
      shell: bash
      run: echo "SEMVER=skip" >> $GITHUB_ENV

    - id: get_semver
      name: Set Semver
      shell: bash
      run: echo "semver=${{env.SEMVER}}" >> $GITHUB_OUTPUT

    - id: output
      name: Set Environment
      shell: bash
      run: echo "environment=${{env.ENVIRONMENT}}" >> $GITHUB_OUTPUT

    - name: Show semver and environment values
      shell: bash
      run: echo "environment=${{env.ENVIRONMENT}}, semver=${{env.SEMVER}}"
