name: Make Package
description: "Make a new package on GitHub"

inputs:
  github_token:
    required: true
    type: string
    description: Github Token
  branch:
    required: true
    type: string
    description: Repository branch


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        ref: ${{ inputs.branch }}

    - name: Set up JDK 11
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven

    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.8.2

    - name: Cache Maven packages
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      shell: bash

    - name: Deploy to GitHub Package Registry
      run: |
        REPO="github::default::https://maven.pkg.github.com/${{github.repository}}"
        mvn -B deploy -DaltReleaseDeploymentRepository="${REPO}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
